### PR TITLE
RideRequest PUT endpoint

### PR DESCRIPTION
**Pull request by ivanke1**
Added RideRequest PUT endpoint

### CODE REVIEW

**Review by Firoc — DISMISSED** [review]
Looks good to me! GJ adding the exceptions for riders, also gj adding the separate stuff for admins / riders

**Review by pconrad — DISMISSED** [review]
LGTM... will test on QA before merging

Update: merge conflicts must be addressed first.

**Review by Anthonypella — APPROVED** [review]
Now that the Merge conflicts are fixed it looks great! Good job handling the exceptions

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
